# after the watch disconnects,
# it waits this number of seconds before closing the program
# and trying to connect again
retry_interval_seconds: 30

# Mi Band device configuration
device:
  name: Xiaomi Smart Band 10 8DCA
  mac_address: 04:34:C3:A4:8D:CA
  auth_key: 13b6840ba233108fd714cbae5f7a3346
  sar_version: 2
  # set this to something like 10000 ms to get enough time to pair it.
  # hopefully that is a one time thing per watch.
  connection_delay_ms: 300

# HTTP server configuration
web_server:
  port: 3000
  vibration_route_name: /vibrate

# i put a couple example patterns here :)
# we should improve them and define specific ones for
# phone calls, notifications, sms messages, etc.
patterns:
  heartbeat:
  - on: true
    duration: 100
    strength: 100
  - on: false
    duration: 125
    strength: 0
  - on: true
    duration: 80
    strength: 75
  - on: false
    duration: 417
    strength: 0
  - on: true
    duration: 100
    strength: 100
  - on: false
    duration: 125
    strength: 0
  - on: true
    duration: 80
    strength: 75
  - on: false
    duration: 417
    strength: 0


  modified_heartbeat:
  - on: true
    duration: 100
    strength: 100
  - on: false
    duration: 125
    strength: 0
  - on: true
    duration: 80
    strength: 75
  - on: false
    duration: 417
    strength: 0
  - on: true
    duration: 100
    strength: 100
  - on: false
    duration: 125
    strength: 0
  - on: true
    duration: 80
    strength: 75
  - on: false
    duration: 417
    strength: 0
  - on: true
    duration: 900
    strength: 80
  - on: false
    duration: 100
    strength: 0
  - on: true
    duration: 100
    strength: 100
  - on: false
    duration: 125
    strength: 0
  - on: true
    duration: 80
    strength: 75
  - on: false
    duration: 417
    strength: 0
  - on: true
    duration: 100
    strength: 100
  - on: false
    duration: 125
    strength: 0
  - on: true
    duration: 80
    strength: 75
  - on: false
    duration: 417
    strength: 0


  sos:
  - on: true
    duration: 80
    strength: 100
  - on: false
    duration: 80
    strength: 0
  - on: true
    duration: 80
    strength: 100
  - on: false
    duration: 80
    strength: 0
  - on: true
    duration: 80
    strength: 100
  - on: false
    duration: 240
    strength: 0
  - on: true
    duration: 240
    strength: 100
  - on: false
    duration: 80
    strength: 0
  - on: true
    duration: 240
    strength: 100
  - on: false
    duration: 80
    strength: 0
  - on: true
    duration: 240
    strength: 100
  - on: false
    duration: 240
    strength: 0
  - on: true
    duration: 80
    strength: 100
  - on: false
    duration: 80
    strength: 0
  - on: true
    duration: 80
    strength: 100
  - on: false
    duration: 80
    strength: 0
  - on: true
    duration: 80
    strength: 100


  sine_wave:
  - on: true
    duration: 60
    strength: 65
  - on: false
    duration: 30
    strength: 0
  - on: true
    duration: 60
    strength: 95
  - on: false
    duration: 30
    strength: 0
  - on: true
    duration: 60
    strength: 95
  - on: false
    duration: 30
    strength: 0
  - on: true
    duration: 60
    strength: 65
  - on: false
    duration: 30
    strength: 0
  - on: true
    duration: 60
    strength: 35
  - on: false
    duration: 30
    strength: 0
  - on: true
    duration: 60
    strength: 35
  - on: false
    duration: 30
    strength: 0
  - on: true
    duration: 60
    strength: 65
  - on: false
    duration: 30
    strength: 0
  - on: true
    duration: 60
    strength: 95
  - on: false
    duration: 30
    strength: 0
  - on: true
    duration: 60
    strength: 95
  - on: false
    duration: 30
    strength: 0
  - on: true
    duration: 60
    strength: 65
  - on: false
    duration: 30
    strength: 0
  - on: true
    duration: 60
    strength: 35
  - on: false
    duration: 30
    strength: 0
  - on: true
    duration: 60
    strength: 35
  - on: false
    duration: 30
    strength: 0


  fibonacci:
  - on: true
    duration: 30
    strength: 50
  - on: false
    duration: 40
    strength: 0
  - on: true
    duration: 30
    strength: 58
  - on: false
    duration: 40
    strength: 0
  - on: true
    duration: 60
    strength: 67
  - on: false
    duration: 40
    strength: 0
  - on: true
    duration: 90
    strength: 75
  - on: false
    duration: 40
    strength: 0
  - on: true
    duration: 150
    strength: 83
  - on: false
    duration: 40
    strength: 0
  - on: true
    duration: 240
    strength: 92
  - on: false
    duration: 40
    strength: 0
  - on: true
    duration: 390
    strength: 100
  - on: false
    duration: 40
    strength: 0

  
  spiral:
  - on: true
    duration: 50
    strength: 60
  - on: false
    duration: 50
    strength: 0
  - on: true
    duration: 81
    strength: 70
  - on: false
    duration: 50
    strength: 0
  - on: true
    duration: 131
    strength: 80
  - on: false
    duration: 50
    strength: 0
  - on: true
    duration: 212
    strength: 90
  - on: false
    duration: 50
    strength: 0
  - on: true
    duration: 343
    strength: 100
  - on: false
    duration: 50
    strength: 0


  rhythm:
  - on: true
    duration: 40
    strength: 75
  - on: false
    duration: 60
    strength: 0
  - on: true
    duration: 60
    strength: 77
  - on: false
    duration: 60
    strength: 0
  - on: true
    duration: 100
    strength: 82
  - on: false
    duration: 60
    strength: 0
  - on: true
    duration: 140
    strength: 86
  - on: false
    duration: 60
    strength: 0
  - on: true
    duration: 220
    strength: 95
  - on: false
    duration: 60
    strength: 0
  - on: true
    duration: 260
    strength: 100
  - on: false
    duration: 60
    strength: 0


  exponential_decay:
  - on: true
    duration: 300
    strength: 100
  - on: false
    duration: 90
    strength: 0
  - on: true
    duration: 180
    strength: 88
  - on: false
    duration: 54
    strength: 0
  - on: true
    duration: 108
    strength: 81
  - on: false
    duration: 32
    strength: 0
  - on: true
    duration: 65
    strength: 76
  - on: false
    duration: 30
    strength: 0
  - on: true
    duration: 39
    strength: 74
  - on: false
    duration: 30
    strength: 0


  rock_beat:
  - on: true
    duration: 120
    strength: 100
  - on: false
    duration: 80
    strength: 0
  - on: true
    duration: 60
    strength: 60
  - on: false
    duration: 80
    strength: 0
  - on: true
    duration: 100
    strength: 85
  - on: false
    duration: 80
    strength: 0
  - on: true
    duration: 60
    strength: 60
  - on: false
    duration: 80
    strength: 0
  - on: true
    duration: 120
    strength: 100
  - on: false
    duration: 80
    strength: 0
  - on: true
    duration: 60
    strength: 60
  - on: false
    duration: 80
    strength: 0
  - on: true
    duration: 100
    strength: 85
  - on: false
    duration: 80
    strength: 0


  waltz:
  - on: true
    duration: 150
    strength: 100
  - on: false
    duration: 100
    strength: 0
  - on: true
    duration: 80
    strength: 50
  - on: false
    duration: 100
    strength: 0
  - on: true
    duration: 80
    strength: 50
  - on: false
    duration: 150
    strength: 0
  - on: true
    duration: 150
    strength: 100
  - on: false
    duration: 100
    strength: 0
  - on: true
    duration: 80
    strength: 50
  - on: false
    duration: 100
    strength: 0
  - on: true
    duration: 80
    strength: 50
  - on: false
    duration: 100
    strength: 0
  

  jons_idea:
  - on: true
    duration: 80
    strength: 25
  - on: true
    duration: 80
    strength: 50
  - on: true
    duration: 80
    strength: 75
  - on: true
    duration: 80
    strength: 100
  - on: true
    duration: 80
    strength: 75
  - on: true
    duration: 80
    strength: 50
  - on: true
    duration: 80
    strength: 25
  - on: true
    duration: 80
    strength: 50
  - on: true
    duration: 80
    strength: 75
  - on: true
    duration: 80
    strength: 100
  - on: true
    duration: 80
    strength: 75
  - on: true
    duration: 80
    strength: 50
  - on: true
    duration: 80
    strength: 25
  - on: true
    duration: 200
    strength: 0
  - on: true
    duration: 50
    strength: 25
  - on: true
    duration: 50
    strength: 50
  - on: true
    duration: 50
    strength: 75
  - on: true
    duration: 50
    strength: 100
  - on: true
    duration: 50
    strength: 75
  - on: true
    duration: 50
    strength: 50
  - on: true
    duration: 50
    strength: 25
  - on: true
    duration: 50
    strength: 50
  - on: true
    duration: 50
    strength: 75
  - on: true
    duration: 50
    strength: 100
  - on: true
    duration: 50
    strength: 75
  - on: true
    duration: 50
    strength: 50
  - on: true
    duration: 100
    strength: 40
  - on: true
    duration: 100
    strength: 25
  - on: true
    duration: 100
    strength: 15
  - on: true
    duration: 100
    strength: 10
  - on: true
    duration: 100
    strength: 5
  - on: true
    duration: 100
    strength: 3
